### ISSUE TITLE
Update noty to 2.3.7

### ISSUE THREAD

**Issue by kwent** [noty/noty-rails#10]
Hi,

Would be nice to upgrade to 2.3.7 ! Thanks for this awesome work !

https://github.com/needim/noty/releases/tag/v2.3.7

Regards

**Comment by PikachuEXE** [comment]
Done in 3a6699e1d2866cfbfab4b41e5581507d636351ac

**Comment by kwent** [comment]
@PikachuEXE So fast ! Thanks a lot !
